### ISSUE TITLE
FEATURE REQUEST: Jump to Letter bar for Music

### ISSUE THREAD

**Issue by ThePapaw** [mikesilvo164/Aeon-Nox-SiLVO#104]
Hey Mike Can you add the 'Jump to Letter bar' to the Audio library using script.embuary.helper like you did with the video?

**Comment by mikesilvo164** [comment]
Added with https://github.com/mikesilvo164/Aeon-Nox-SiLVO/commit/7dc4fdd32d2645cf20ab2f2bb02a2b2076c71a4d

Pretty sure I got all the views but if one doesn't work let me know.
