### ISSUE TITLE
Custom nodes not displayed

### ISSUE THREAD

**Issue by GregDiego** [mikesilvo164/Aeon-Nox-SiLVO#106]
Hi
I used to create and use custom nodes in previous version using library node editor.
Now, even creating it manually, custom nodes are not displayed when setting up action menu.
It seems that  "AcitvateWindow(Videosdb://....." is used instead of "AcitvateWindow(library://....."

Thanks for your great skin.

Greg

**Comment by mikesilvo164** [comment]
Not sure if this is still an issue or not so closing it
