### ISSUE TITLE
Feature Request: Side-Blade Tab

### ISSUE THREAD

**Issue by mrgsi** [mikesilvo164/Aeon-Nox-SiLVO#111]
It would be a handy feature to have a clickable tab to pull out the left hand Side-Blade menu as an alternative to only using directional keys to force it open. I've seen it in other skins and have used it a lot. It also helps identify when and where the side blade is available.

**Comment by mikesilvo164** [comment]
There is already something in the skin. There is a hamburger button at the top of the screen to indicate when the sideblade can be opened. It is also clickable. Lastly there is a setting to auto open the side menu when hovering over it with a mouse.
