### ISSUE TITLE
"Manage" menu item missing

### ISSUE THREAD

**Issue by My-Random-Thoughts** [mikesilvo164/Aeon-Nox-SiLVO#128]
The menu list for a movie/tv item is missing the "Manage" option, instead it has "Select Animated Art" - even though I have turned that option off in the settings.

Without Manage, there is no "Edit title", etc, so I can't make changes to some of the items.
My selected view is RightList, but it's the same for List too.

Using LibreElec 9.2.6 (Kodi 18.9)
Skin Version: 7.0.9

**Comment by ThePapaw** [comment]
Have you considered updating to a newer version? I think the current version is v7.9.6.

**Comment by My-Random-Thoughts** [comment]
I am using the version that is available from within the Kodi menu, is this not kept up to date?

**Comment by My-Random-Thoughts** [comment]
OK, not sure what I did, but it's showing up correctly now!  Very strange.  Version numbers are still the same as above, but I now have a "Manage" menu item.
