### ISSUE TITLE
library data provider error kodi matrix

### ISSUE THREAD

**Issue by ghost** [mikesilvo164/Aeon-Nox-SiLVO#131]
The library data provider addon needs to be updated for matrix.
I always get an error when returning to the homescreen.

Very easy to reproduce.

Just reboot and when finished booting you get an error.

**Comment by robbie347** [comment]
Crashing in Kodi 19.0 with Windows 10 and Linux versions after movies and music videos installed. 
Referred the Linux crash log to CoreELEC Support, who (also) advised that the used addon service.library.data.provider is not Matrix compatable.
