### ISSUE TITLE
Wrong country flags for subtitles

### ISSUE THREAD

**Issue by frxx696** [mikesilvo164/Aeon-Nox-SiLVO#133]
Hi, is it possible to change wrong flags icons for countries - Bosnian and Serbian?

![subtitles](https://user-images.githubusercontent.com/80256209/110313408-aae18e80-8006-11eb-80e5-28a076509e3b.jpg)

**Comment by mikesilvo164** [comment]
What flags are they supposed to be?

**Comment by mikesilvo164** [comment]
Closing until some clarification on which flag isn't correct and what it is supposed to be. 
Feel free to reopen if you can provide that info :)
