### ISSUE TITLE
Is it optimized for the Matrix?

### ISSUE THREAD

**Issue by audiosistem** [mikesilvo164/Aeon-Nox-SiLVO#134]
Hello!My configuration is ok in windows, but in android (xiaomi device), although it is configured well, I can only access video addon ... delete Aeon skin and everything works.Possible, in the future,for the Matrix optimization?
Thank you for your work!

**Comment by flensburg2** [comment]
I think , what you mean to say is that the gui is not working on android touchscreen? This was the case for me, "videos" was marked and regardless where I try to press, it will still only be on "video" . Had to delete aeon-nox-silvo folder to reset.

**Comment by lolgithub** [comment]
I confirm that Aeon Nox Silvo does not work on Kodi Matrix currently. I am unable to select any menu from the main menu, except the menu that was selected when I change the skin.

**Comment by audiosistem** [comment]
Wrong. It works. But it is not optimized for 19. Only some phones and tablets do not pair with Aeon. PC, TV box and smart TVs (android) work.

**Comment by lolgithub** [comment]
I should have been more specific. I am on a Amazon Fire 7th generation HD 10 on Fire OS 5.6.8.0, and it most certainly does not work, as described above. Leia works.

**Comment by audiosistem** [comment]
I just said ... it's not optimized. Some devices work, others don't.

**Comment by audiosistem** [comment]
![skin Silvo](https://user-images.githubusercontent.com/6246768/125168442-47cb5880-e1ae-11eb-9567-8fc295104c8b.jpg)

Hi, you can look, maybe you can find a solution. If it only appears to me, ignore it. Thank you!

**Comment by audiosistem** [comment]
Moving to 19.2, the skin of Aeon Nox Silvo has become for me again, number 1. Thank you!
