### ISSUE TITLE
Recently added TV widget does not select highlighted episode

### ISSUE THREAD

**Issue by velkrosmaak** [mikesilvo164/Aeon-Nox-SiLVO#137]
The recently added TV widget would previously allow me to select a recently added episode from the home screen, and then this would go to that show's episode folder, with the episode highlighted. Now when I select a recently added episode, I get the TV menu, with whichever show was previously selected. 

The config is a straight Recently Added TV Episodes widget on the TV home menu. 

Thanks for any help! :)

**Comment by mikesilvo164** [comment]
When selecting a recently added episode directly from the widget, for me, it plays the file.
