### ISSUE TITLE
Grey overlay in lyrics

### ISSUE THREAD

**Issue by Raul824** [mikesilvo164/Aeon-Nox-SiLVO#141]
Kodi Matrix 19

tested on: 
librelelc rpi 4.
windows 10.

there is a grey overlay in lyrics.
I have tried toggling the disable background overlay in cu lyrics but it didn't worked.
Its working in rapier and aeon-tajo.

![image](https://user-images.githubusercontent.com/51978647/119705127-bde45c00-be9b-11eb-92c1-de8efdce2944.png)

**Comment by StealthEmissarI** [comment]
awesome 、how to do that >_<

**Comment by mikesilvo164** [comment]
This should've been fixed with 84f8894e02078db9de7c15e7611128c91995cb41
