### ISSUE TITLE
Skin Info Service and Settings > Video OSD > Auto Hide OSD problem with cloned values

### ISSUE THREAD

**Issue by UTAVATU** [mikesilvo164/Aeon-Nox-SiLVO#148]
Dear Friends

There is a problem, when you go to Settings > Video OSD > Auto Hide OSD and active it... First you need to install Skin Info Service.

What is the problem?

1. When you try to choose for example 7 seconds, it will show Inactive.
2. When you try to choose anything from Inactive to 90 seconds and then you go for example to:
a) Live TV > Logo - and click to choose values there you will see cloned options from Settings > Video OSD > Auto Hide OSD
b) Main menu > Aeon Nox main menu layout - and click to choose values  there you will see cloned options from Settings > Video OSD > Auto Hide OSD
c) every other options in Settings of the Aeon Nox: SiLVO, where there is a possibility of choosing some options like in a) and b) you will always see cloned options from Settings > Video OSD > Auto Hide OSD

I don't know, if it's related with Skin Info Service or just with some code in Variables like below:
```
<variable name="AutoHideVideoOSDLabelVar">
		<value condition="!String.IsEmpty(Skin.String(SkinInfo.AutoCloseVideoOSD))">$INFO[Skin.String(SkinInfo.AutoCloseVideoOSD)] $LOCALIZE[31090]</value>
		<value>$LOCALIZE[13113]</value>
	</variable>
```

Thank you in advance for your help and support.

Sincerely

**Comment by mikesilvo164** [comment]
Fixed with 0ff71c9376c652873945914e4e0815f2ca6629a7
Thanks
