### ISSUE TITLE
Weather Widgets broke

### ISSUE THREAD

**Issue by mrgsi** [mikesilvo164/Aeon-Nox-SiLVO#149]
I received an update of the Skin Shortcuts module yesterday and it looks like it broke the weather widgets. This happened on both my devices. All I get is the images of sun and cloud, no temperature or day of the week information. I'm assuming it was the skin shortcuts module as it was the only thing related that was changed in my system running skin version 8.0.1 on one device 8.0.0 on the other.. It also changed the widget format from it's normal "Panel" display to "Panel Extended" which I thought was really bizarre.

**Comment by audiosistem** [comment]
> I received an update of the Skin Shortcuts module yesterday and it looks like it broke the weather widgets. This happened on both my devices. All I get is the images of sun and cloud, no temperature or day of the week information. I'm assuming it was the skin shortcuts module as it was the only thing related that was changed in my system running skin version 8.0.1 on one device 8.0.0 on the other.. It also changed the widget format from it's normal "Panel" display to "Panel Extended" which I thought was really bizarre.

![Weather](https://user-images.githubusercontent.com/6246768/142751040-cccc78cb-1ab6-4936-85e9-acb8245ada26.jpg)

**Comment by mikesilvo164** [comment]
Can you try changing an option for the weather widget and letting it rebuild?

**Comment by G-streamer** [comment]
Okay I changed the settings to match yours, backed out of settings and restarted Kodi just to make sure. Just to clarify, the widgets loose displayed text data of the weather forecast and only display the images. I am using the Gismeteo weather service. Same issue on both my Windows 10 PC and Nvidia Shield Pro. It fixes it when fall back to skinshortcuts 1.1.5 as shown in the following image comparison.
![image](https://user-images.githubusercontent.com/61789563/142763027-9862d764-933b-4b97-901b-0f8f9761a036.png)

**Comment by mikesilvo164** [comment]
Without any debug logs I can’t know what’s going on. Please enable Kodi debug log as well as the skin shortcuts debugging. If it’s a skin shortcuts thing and not something I can change in the skin then you’ll likely need to post an issue there or about it on the Skin Shortcuts forum.kodi.tv thread.

**Comment by audiosistem** [comment]
> Okay I changed the settings to match yours, backed out of settings and restarted Kodi just to make sure. Just to clarify, the widgets loose displayed text data of the weather forecast and only display the images. I am using the Gismeteo weather service. Same issue on both my Windows 10 PC and Nvidia Shield Pro. It fixes it when fall back to skinshortcuts 1.1.5 as shown in the following image comparison. ![image](https://user-images.githubusercontent.com/61789563/142763027-9862d764-933b-4b97-901b-0f8f9761a036.png)

![Weather 2 widget](https://user-images.githubusercontent.com/6246768/143545933-8d275251-49b2-4707-96c9-822012e23faa.jpg)
![Weather](https://user-images.githubusercontent.com/6246768/143545936-b052aec2-95f2-43ab-b762-34164675595c.jpg)
My weather settings.
