### ISSUE TITLE
Watched Status Indicatator Missing On Movies

### ISSUE THREAD

**Issue by jwor80** [mikesilvo164/Aeon-Nox-SiLVO#151]
In version 8.0.1 running Kodi 19.3 the watched status indicator is missing on movies.  It appears to work for TV Shows.  I have verified that the watched status indicator works correctly for movies using estuary, and the setting is enabled in the aeon nox silvo settings.

**Comment by mikesilvo164** [comment]
I can't find any issues with status indicators.
