### ISSUE TITLE
Autoplay Music In fullscreen Missing

### ISSUE THREAD

**Issue by jwor80** [mikesilvo164/Aeon-Nox-SiLVO#153]
Kodi 19.3 and Aeon nox Silvo 8.0.1 is missing the option that was in 7.0.9 to autoplay music in fullscreen.

System > Interface > Configure Skin > Customization > Music OSD > Autoplay music in fullscreen

**Comment by mikesilvo164** [comment]
This is a core setting now and can be enabled in the Kodi settings

**Comment by STPKITT** [comment]
Since I can't find it anywhere in Kodi's settings I guess it may have become an official option but only via advancedsettings.xml or so.
So IMO the skin should offer that option for the user to configure it via the GUI.
Correct me if I'm wrong about that setting not being in the stock Kodi GUI!
