### ISSUE TITLE
Contributing a new feature: user adjustable limit to background fanart count

### ISSUE THREAD

**Issue by zacharyfreeman70** [mikesilvo164/Aeon-Nox-SiLVO#155]
I've got some free time over the next few days and would like to contribute a new feature. I'd like to let the user adjust how many random movie fanarts are rotated through by the "Kodi random movie fanart" setting located in the following menu hierarchy:

_Interface -> (Expert Mode) -> Skin -> Configure Skin -> Main Menu -> Setup the Aeon Nox main menu -> Movies -> Select background: Kodi random movie fanart._

Currently, when "Kodi random movie fanart" is selected, the skin loads 25 random fanarts and then rotates through them at whatever speed the user sets (default is currently 7 seconds I think). A quick grep through the source code leads me to believe that this limit of 25 is hardcoded here:
https://github.com/mikesilvo164/Aeon-Nox-SiLVO/blob/dd746c6d2d9835d3ae6c2e480b7fbfa6097fd89e/16x9/Includes_Backgrounds.xml#L179

Indeed, changing `limit="25"` to `limit="50"` results in the skin looping through 50 random fanarts instead of 25. A few questions for you:

1. Are you guys accepting pull requests for new features? I see there are 8 pending pull requests already, some of which are several quarters old. I don't want to waste your time or mine with creating one if it'll just sit unmerged or be ignored.
2. Any insight into why 25 was chosen here for a hardcoded limit over any other number? Any concerns in letting a user 2x this figure or even 10x or 100x it? (Frankly, as long as the user has sufficient hardware to handle it, I'm all for letting them go wild.)
3. Is `16x9/Includes_Backgrounds.xml` the only location where this limit is hardcoded or will I need to make similar adjustments to other constants elsewhere?

**Comment by mikesilvo164** [comment]
Hardcoded to limit resources used. If more varied fanart rotation is wanted there is support for [script.grab.fanart](https://kodi.wiki/view/Add-on:Grab_Fanart)

Just need to select the other fanart options that do not say Kodi in front of them when that script is installed:
![img](https://i.imgur.com/lp83OBf.png)
