### ISSUE TITLE
System info widget

### ISSUE THREAD

**Issue by neogamaes** [mikesilvo164/Aeon-Nox-SiLVO#156]
Hi,

I finally switched from Leila 18.9 to Matrix 19.3 (mainly for audio passthrough reason) and I have notice few things still not working properly:
- the "system info" widget does not show any values but just few images (exact same issue on my phone and on my Fire TV stick). Same problem for CPU usage given in the information bar on the main menu ("CPU usage: not available")
- finally, I got sometimes a strange issue on my phone when i scroll the horizontal menu: the highlighted item menu (such as Movies, TV show, Weather...) is not centered anymore.

Beside this, so far so good and thank you for this great work.

Best wishes 👍

**Comment by mikesilvo164** [comment]
I cannot replicate this.
