### ISSUE TITLE
file manager

### ISSUE THREAD

**Issue by GravuTrad** [mikesilvo164/Aeon-Nox-SiLVO#163]
Hello.

Thanks for this great skin.

Impossible to find the file manager in this skin. Is it anywhere or is it a bug?

Thanks

**Comment by mrgsi** [comment]
Any Kodi command can be added to the Menu or Sub menu. Just edit the skin menu and add the custom command: ActivateWindow(FileManager)

**Comment by GravuTrad** [comment]
I found it. it is not really accessible but i found it. It's in "system" and in the menu that appear bottom. It's really not intuitive. It could be added in the "system" part directly too.
