### ISSUE TITLE
Portugal ratings

### ISSUE THREAD

**Issue by Pemicope** [mikesilvo164/Aeon-Nox-SiLVO#165]
Hello.

I love your skin, but there's no ratings for Portugal.
You can check here: https://rating-system.fandom.com/wiki/Portugal_movie_rating_system, if you decide to add them.

Thank you.

**Comment by mikesilvo164** [comment]
I would need the ratings images to add them.
161x109 centered with transparent background, preferably in both B&W and color if it exists.

**Comment by Pemicope** [comment]
Hi, sorry I couldn't find any icons. I searched everywhere...
I'll keep using the ratings from the US. Thanks anyway. Keep up the good work!

**Comment by Pena1267** [comment]
I think you’ve got the wrong person 


Best Regards 

On Wednesday, January 18, 2023, 7:42 PM, mikesilvo164 ***@***.***> wrote:




I would need the ratings images to add them.
161x109 centered with transparent background, preferably in both B&W and color if it exists.
