### ISSUE TITLE
video calibration doesn't work in v20.

### ISSUE THREAD

**Issue by ShadwDrgn** [mikesilvo164/Aeon-Nox-SiLVO#169]
Using a steam deck, but not sure if that matters. see https://github.com/xbmc/xbmc/issues/22688

**Comment by manolischania** [comment]
> Using a steam deck, but not sure if that matters. see [xbmc/xbmc#22688](https://github.com/xbmc/xbmc/issues/22688)

it seems that you don't use the git version that is updated
