### ISSUE TITLE
[FeatureRequest] Synchronise the EPG-menus (channel and Full-EPG)

### ISSUE THREAD

**Issue by walterheisenberg** [mikesilvo164/Aeon-Nox-SiLVO#19]
Please synchronise the EPG-menus for channel-EPG and Full-EPG
There are some entries missing in channel-EPG, like:
- "Search similar" ("Nach ähnlichem suchen" in ger)
This is useful, if you have a program you want to watch, but not now and you are searching for a rerun of it on another channel. Then you don't have to switch to Full-EPG, search the channel and the program and select "search similar"
- "Add timer" ("Timer hinzufügen" in ger)
With this, you can select "Series recording", when a TV-Show is aired on a channel and you want to record it every week at the same time.
Here are two pics, you can compare: http://imgur.com/a/4hpBy

I don't know if this all is possible with the skin, or this has to be done in kodi itself, but I wanted it to be mentioned ;)

**Comment by sveni-lee** [comment]
Hello,
Isn't it the information you were looking for? Read about it here <http://pykontycri.dwayneclemmons.com/aeptr?89hdr>

Kind regards, sveni_lee@gmx.de

**Comment by mikesilvo164** [comment]
@sveni-lee Why post a spam link? Please correct the link or I will have to delete it.

**Comment by walterheisenberg** [comment]
I close this issue, because I have created a nicer PVRInfo with corrected buttons
No PR yet ...
