### ISSUE TITLE
jarvis-widget-dev Branch

### ISSUE THREAD

**Issue by mistervee** [mikesilvo164/Aeon-Nox-SiLVO#20]
### **Requires script.skinshortcuts v1.0.7**

**Current Status**
- Management dialog _working_
- Global settings _working_
- Widgets _working_ 
- Navigation _working_

**Strings to be removed** 
- Removed strings below only from US lang file. Not sure how this all works with transifix.
- 31757
- 31753
- 31743
- 31739
- 31735

Widget Strings are from 31700 to 31759

**Comment by mistervee** [comment]
@mikesilvo164 Adding the widget settings in atm. I need to do the localized strings and some will be remove just thinking would it be best if I were to have a separate range for the widgets??

I was thinking from 31700 to 31799.

**Comment by mikesilvo164** [comment]
Should be great, looks like a good size block with room on either side . Would you like me to do anything? If you have any specific task you'd like me to handle, I am all yours :smiley: 

While I have you hear... Wanted to ask if you wanted to take over the Live TV part? I do not use it so you would have carte blanche to add/change whatever you feel like. I am only asking since you previously mentioned wanting to work on other things besides Widgets :stuck_out_tongue_winking_eye:

**Comment by mistervee** [comment]
I would say at his point there is not much you can do. I just need to get the basic functions working, then I would say some help would be great. I'll keep the first post updated with things that need to be looked at after a whole bunch of copying and pasting from madnox.

All good on the live tv part. The widgets I am hoping shouldn't take to long to get implemented. Probably a couple of weeks. After that I can look at the live tv and the pending PR's.

**Comment by mikesilvo164** [comment]
@mistervee Do you mean my changes to RightList or just an overall improvement? :smiley:

Any suggestions?

**Comment by mistervee** [comment]
@mikesilvo164 Library views are just perfect. So I would say overall. I spent so much time on madnox I didn't get a chance to check out the updates over the past month and a bit. So no suggestions I cant fault it :+1: 

BTW: my new pet hate in life is localized strings.

**Comment by mistervee** [comment]
@mikesilvo164 please ignore the pull request.

**Comment by schimi2k** [comment]
Good morning Gentlemen,
i can try my best for german translation later ... will post the results here
( have some homework first )
cheerz
schimi the kraut

**Comment by schimi2k** [comment]
just a small info - the strings.po is not a xml code ;) 
your comments "break" the english language file - if you want to comment out a line, add a "#" in front
i fixed this, because my PoEdit always crash when i try to merge the files ;) 
i will send you the english and the german files here when i am done with translate

**Comment by schimi2k** [comment]
okay,
here is the english and the german language file - maybe please test before PR ;)

https://dl.dropboxusercontent.com/u/26590569/SILVO/language.rar

i try to use the german words you are use for other lines before
( we use some others for some items - but this is a german problem ... too many words for the same thing ) 
with this new english file they can use it with PoEdit again 
and you can see directly what lines i commented out when you load it with a txt editor
if you need more - just say something :)

**Comment by bartolomesoriano** [comment]
@all, I will be providing Spanish translation in about an hour.  Happy to help with Nox Silvo!

**Comment by bartolomesoriano** [comment]
@all, here is the updated Spanish strings.po.  I based this on the English on that @schimi2k posted earlier.  
[Spanish.zip](https://github.com/mikesilvo164/Aeon-Nox-SiLVO/files/152921/Spanish.zip)

**Comment by mikesilvo164** [comment]
@mistervee Rebasing would be better but in the end it doesn't matter since I will probably squash it into one commit when it is time to cherrypick it. I can rebase for you whenever you need and don't have any unpushed changes :smiley:

@schimi2k @bartolomesoriano Thanks a bunch gentlemen, you guys are the best, the best of the best, with honors! :grinning:

**Comment by schimi2k** [comment]
yes we are :) muhahaha
just a realy tiiiiiny thank you for all the help you guys gave us !

**Comment by mistervee** [comment]
@schimi2k @bartolomesoriano Awesome work on the translations. Many, many thanks.

@mikesilvo164 Thanks mike. You could rebase any time, if you are not changing the overrides, template or includes widgets xml's.

**Comment by mistervee** [comment]
@mikesilvo164 Language flags are something that is coded for the widget 'oninfo' (not working atm though). Is this something that you would consider adding to the skin overall? This can now be handled by the image resource addon as flags are available to download. I can comment it out for future use or remove it entirely or just add the support for it in the widget if a user has a language flag pack downloaded.

**Comment by mikesilvo164** [comment]
@mistervee Sorry for the late reply... I am not a fan of the flags but if you want to show them only in the Widget info screen when it is installed, I wouldn't mind :wink: 
Your call my friend :smiley:

**Comment by mistervee** [comment]
@mikesilvo164 Sorry myself for the late reply and RL has gotten in the way of skinning. Must of missed the notification in my inbox.

In that case I will remove them. Will be easier and I am not a fan myself.

**Comment by mistervee** [comment]
@mikesilvo164 
One more question.

Do you still want to keep the nox default widgets? (meaning the advanced setting)

Just complicates things a bit if they need to be still included. Besides that I have not seen 1 question or comment in the forum relating to the default widgets. I seem to get the impression the advanced widgets used by the majority of people.

**Comment by mikesilvo164** [comment]
@mistervee Nah, kill em' :smiley:

Yours are far superior and I originally only wanted them to maintain similarities between vanilla Nox 5. Skin will still inherit from upstream but it has become it's own beast now :wink:

I also liked my modded default weather widget so I had wanted to keep it around.

**Comment by mistervee** [comment]
@mikesilvo164 Awesome. Makes one headache go away.

When you get a chance, check out the vertical menu and how the extended widgets work. This came from your suggestion way back.

**Comment by mikesilvo164** [comment]
@mistervee Already did and I think it works perfectly. Great job!

My only nitpicky thing is when opening 1199 and it shrinks to fit that width so to me it looks a little off... Not a big deal or anyhthing just looks a little weird to me.

**Comment by mistervee** [comment]
@mikesilvo164 I'll agree with you on that. I will make the changes.

**Comment by mistervee** [comment]
@mikesilvo164 Changes Done.

Thoughts?

**Comment by mikesilvo164** [comment]
@mistervee Me likey :smiley:. 
Only other thing is the global search icon. Maybe when menu item has extended widget keep the same slide animation. As stated earlier this is just nitpicky stuff.

If possible I'd would like to merge ASAP cause it is hard for me to fix things concerning the Widgets since I don't really use them unless testing. So I'm thinking merge then a push to repo and then if any issues pop up users can specify the what and where so it would be easier for me to find and fix.

**Comment by mistervee** [comment]
@mikesilvo164 

Fixed the slide animation.

Got it ASAP. No problem at all. Very very close to finishing.

**Comment by mistervee** [comment]
@mikesilvo164 

Another thing to note is, the user will have to reset each and every widget when upgrading at a minimum. 

It would be better to reset the whole main menu though so any left over widget values from the previous version are reset. But the former should work in most cases.

**Comment by mikesilvo164** [comment]
@mistervee Wondering if I should force reset menus on startup and just deal with the fallout... Some users will be pissed but shit happens :wink:
What do you think?

Just give me the word when it is ok to merge and once we sort out whats best to do with the menus I'll squash and merge it :smiley:

**Comment by mistervee** [comment]
@mikesilvo164 I'Il think you will get a fall out either way. The menu will work with out an issue, just the widgets. So may be not a force reset of the main menu, just a big fat warning to people that they need to reset there widgets but recommend main menu reset. 

On the other hand a forced reset as an option might work.

I'm getting close its just the info dialog holding me back. The darn buttons I have so much trouble getting them to work with all the possible widget options. I might have to leave some things as they are even though I know they are not 100% functional. If I could only make the widget container button click as a property it would be all too easy. 

So very soon I will give the word to merge. :)

**Comment by mistervee** [comment]
@mikesilvo164 

All Done. Ready to Merge :grinning:

Note my comment at the top of the page regarding skin strings.

**Comment by mikesilvo164** [comment]
@mistervee  Awesome news! Will check out the strings file soon :smiley:

Been working on a way to warn about the update and I could use your opinion on it if you have some time?

**Comment by mistervee** [comment]
@mikesilvo164 sure. skype maybe?. send me a message when you ready.
