### ISSUE TITLE
No display on Asian characters?

### ISSUE THREAD

**Issue by colinlee2016** [mikesilvo164/Aeon-Nox-SiLVO#23]
Hi thank you for a lovely skin for Kodi by yourself! Any chance you could add support for the Asian characters please? Tried install Arisl fonts but still not able to display Asian characters!

**Comment by colinlee2016** [comment]
Sorry there was typo... Reopen the issue...

Hi thank you for a lovely skin for Kodi by yourself! Any chance you could add support for the Asian characters please? Tried install Arial fonts but still not able to display Asian characters! Confluence was ok to display Adian characters with Arial but not Aeox Nox :(. Please help?

**Comment by mikesilvo164** [comment]
Arial is already an option in the skin
