### ISSUE TITLE
FileBrowser.xml

### ISSUE THREAD

**Issue by MK-IV** [mikesilvo164/Aeon-Nox-SiLVO#41]
Hey Mike, can you add a few things to this file please:

I needed to add `<selectedcolor>$VAR[ThemeLabelColor]</selectedcolor>` when calling from my add-on to enable highlighting multiple files (calling browse images) along with adding a font color to keep the label when highlighted.

**Comment by mikesilvo164** [comment]
No support for builds or whatever the hell you are doing with my skin 😞...
