### ISSUE TITLE
Advanced Emulator Launcher

### ISSUE THREAD

**Issue by ShadwDrgn** [mikesilvo164/Aeon-Nox-SiLVO#42]
There're only "list" and "icon" views in advanced emulator launcher. I would have expected all of the usual lowlist etc. views to be there. It has support for a great deal of assets and some cool possibilities for skinners. Any chance for support for this? Particularly with Retroplayer merge coming soon this would be amazing.

**Comment by mikesilvo164** [comment]
I will support RetroPlayer when merged but I will likely not support add-ons like Advanced Launcher or AEL..

Sorry.
