### ISSUE TITLE
Channelnumbers

### ISSUE THREAD

**Issue by Leatherface75** [mikesilvo164/Aeon-Nox-SiLVO#45]
Would be nice if channelnumber digits could be changed from 3 to 4 numbers in channel selection.
If you have satellite for example you often have a few tousand of channels.

**Comment by Leatherface75** [comment]
This show the problem better

http://i.imgur.com/ZCdyKFx.png

**Comment by Leatherface75** [comment]
Fixed it myself and made a pull request

**Comment by mikesilvo164** [comment]
Check your PR for info.
