### ISSUE TITLE
Cpu thrashing and gradual memory leak

### ISSUE THREAD

**Issue by draconis244** [mikesilvo164/Aeon-Nox-SiLVO#46]
Kodi 17 from debian sid 

Started off with estuary skin but came from kodi 16 on aeon nox ...so installed vanilla nox ....had freezing problems but fine in estuary. ...found your build of nox works beautifully freezing gone .....but CPU sits at around 40% even when idle and over the space of a day or so eats nearly 80% ram after reboot goes back to a sensible 8% ram but creeps back up slowly ....doesn't happen in estuary on either cpu or ram ....using latest tvheadend on remote server and the kodi-pvr-hts from debian sid .....if you need logs I can supply them

**Comment by mikesilvo164** [comment]
Yes, please supply a log but seek support in the Kodi forum thread. There is no support for issues with Piracy related Add-ons.

Thanks.
