### ISSUE TITLE
FEATURE REQUEST - Additional Video Info

### ISSUE THREAD

**Issue by qazero** [mikesilvo164/Aeon-Nox-SiLVO#48]
Firstly, I love your skin! Secondly, is there any chance you can add an additional layout for the video info when selecting a movie similar to the screenshot below? Thanks

![image](https://cloud.githubusercontent.com/assets/10906010/24812056/dbe6bf76-1b85-11e7-94c0-4cd5f80122e8.png)

**Comment by mikesilvo164** [comment]
I already have a new redesign of the Video Information Screen and I am content with it how it currently looks  😃 
![image](http://i.imgur.com/0GqBrRw.jpg)

**Comment by Leatherface75** [comment]
Would be nice to have this for EPG too.
