### ISSUE TITLE
Music fanart scaling

### ISSUE THREAD

**Issue by ThumberDK** [mikesilvo164/Aeon-Nox-SiLVO#50]
Hey Mike,

First off, thanks again for the best skin for Kodi!

I reported this issue on the forum awhile back, and i think you added a fix, but i got sidetracked by real life issues and never got into it. But i still seem to have this issue, on older artists with odd size pictures, they are scaled wrong.

Im using Kodi 16.3 and Silvo Nox 6.0.7 on a Nvidia Shield. Have the issue too tho on my Windows box.

Let me know what you need to troubleshoot this and im available to test out new git versions offcourse.

I thought it best to create the post here, to avoid the clutter of the forum, hope that is ok.

**Comment by mikesilvo164** [comment]
Closing this. If it is still a problem please open a new issue.
