### ISSUE TITLE
Hello Mike, OSD Menu Buttons/Icons not showing.

### ISSUE THREAD

**Issue by Spacetout** [mikesilvo164/Aeon-Nox-SiLVO#51]
I'm Using a RPI 3, Latest Version of Silvo, and Kodi v.17.3.
When I am watching video content and press the "M" button to open the OSD menu, nothing shows up.
The placeholder pops up, but no icons to press. Also when I press "W" to mark a tv or movie in my Library as watched, isn't working either.
Thank You Sir.

**Comment by mikesilvo164** [comment]
Try reinstalling the skin. I tested and all is working fine on a fresh install.

If a reinstall fixes please close this issue.
