### ISSUE TITLE
Support for sub-title in EPG

### ISSUE THREAD

**Issue by Leatherface75** [mikesilvo164/Aeon-Nox-SiLVO#54]
In imported EPG in TVheadend it looks like this

[https://i.imgur.com/orCvo91.png](https://i.imgur.com/orCvo91.png)

In red you can see "Ishockey: SHL 17/18: Karlskrona HK - Örebro HK"

With other skins like default Estuary it shows sub-title as it should
[https://i.imgur.com/x93DvvH.png](https://i.imgur.com/x93DvvH.png)

With Aeon Nox Silvo it looks like this
[https://i.imgur.com/fcGcrwn.png](https://i.imgur.com/fcGcrwn.png)

"Ishockey: SHL 17/18: Karlskrona HK - Örebro HK"
Is missing there and it's really an issue if you can't see which match it is etc.

**Comment by mikesilvo164** [comment]
@Leatherface75 I am actually working on PVR stuff right now. I will push an update for you to test sometime today.

**Comment by Leatherface75** [comment]
Ok sounds good

**Comment by mikesilvo164** [comment]
@Leatherface75 Did a redesign, mind taking it for a test ride and see if I missed anything?

**Comment by Leatherface75** [comment]
Sub-title works in channellist when pressing 'h' in info but the other channellist with 'c'.
When pressing INFO while watching the channel it doesn't show either.

Path and Filename maybe could be removed from information.
Icon for the program when available would be nice too.

**Comment by mikesilvo164** [comment]
I am adding that now. 
I can remove those.
What icon do you mean?

**Comment by Leatherface75** [comment]
Some grabbed XMLTV data have icon src for every program and i have seen some other skins have it so i know Kodi supports it.

**Comment by mikesilvo164** [comment]
does estuary show it?

**Comment by Leatherface75** [comment]
I just checked seems not but Aeon Nox Madnox supports it when i checked.

**Comment by Leatherface75** [comment]
[https://i.imgur.com/4WWBce3.png](https://i.imgur.com/4WWBce3.png)

**Comment by mikesilvo164** [comment]
Then it probably relies on Skin Helper and I may add that one day but not until the maintainer of the script pushes updates to the Kodi repo on a more regular basis.

**Comment by Leatherface75** [comment]
Ok maybe and i guess there is other interesting things that could be added but for now i am happy with this sub-title thing fixed.

**Comment by mikesilvo164** [comment]
@Leatherface75 Can you post a pic of Estuary INFO while watching the channel so I can see what is missing?

**Comment by Leatherface75** [comment]
[https://i.imgur.com/tMxdzIc.png](https://i.imgur.com/tMxdzIc.png)

Maybe S4 E17 can look better than there.

**Comment by Leatherface75** [comment]
I see you did some updates already i'll test it.

**Comment by mikesilvo164** [comment]
I believe this can be closed now.
