### ISSUE TITLE
MPAA rating for NOT RATED is skipped/ left blank

### ISSUE THREAD

**Issue by QuattroGam3r** [mikesilvo164/Aeon-Nox-SiLVO#58]
I scrape with Mediaelch so not sure how other scrapers pull info, but IMDB movies with the MPAA cert. NOT RATED are left blank in the skin. To fix this I had to edit the Variables.xml to add a line after #851 to state:
`<value condition="String.Contains(ListItem.MPAA,NOT RATED)">NR.png</value>`

**Comment by QuattroGam3r** [comment]
Update- That only worked for the first movie entry. I had to remove my line and edit line #852 from Rated to NOT RATED. Now all NOT RATED movies show NR flags

**Comment by mikesilvo164** [comment]
I don't think this is still an issue so closing this. Feel free to open a new one if it is still a problem.
