### ISSUE TITLE
Custom option Trailers

### ISSUE THREAD

**Issue by kodiultimate** [mikesilvo164/Aeon-Nox-SiLVO#59]
Hi,

Just wondering if would possible to add custom Trailers option on home menu which is activated by ActivateWindow(1120)
I currently using modded skin bello 6 but this Trailers option is brilliant and uses Extended Mod Info for information.

I can support if needed.

![jhjh](https://user-images.githubusercontent.com/32402420/37008178-3819c930-20e1-11e8-8390-78532779c04a.jpg)

Here is an Custom_Trailers.xml from bello:

<?xml version="1.0" encoding="UTF-8"?>
<window id="1120">
	<defaultcontrol always="true">4000</defaultcontrol>
	<controls>
		<include>BackgroundContent</include>
		<include>Trailers_Fanart</include>
		<include>BackgroundVignette</include>

    
    
    
		<control type="grouplist" id="4000">
			<left>0</left>
			<top>95</top>
      <width>1280</width>
      <height>560</height>
      <orientation>vertical</orientation>
      <scrolltime tween="sine">450</scrolltime>
      <itemgap>0</itemgap>
	    <include>InfoDialogsVisible_ZoomAnimation</include>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow1)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="4100"/>
		      <param name="provider_icon" value="icons/tmdb.png"/>
		      <param name="provider_name" value="$LOCALIZE[31256] (The MovieDB)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(4100).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Posters">
		      <param name="container_id" value="4100"/>
		      <param name="onup" value="5200"/>
		      <param name="ondown" value="4200"/>
		      <param name="content" value="plugin://script.extendedinfo?info=incinemamovies"/>
		    </include>
			</control>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow2)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="4200"/>
		      <param name="provider_icon" value="icons/youtube.png"/>
		      <param name="provider_name" value="20th Century Fox (YouTube)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(4200).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Landscape">
		      <param name="container_id" value="4200"/>
		      <param name="onup" value="4100"/>
		      <param name="ondown" value="4300"/>
		      <param name="content" value="plugin://script.extendedinfo?info=youtubeplaylistvideos&amp;&amp;id=PLfPBohF1uFwoO5wBnYD67i0pbZ6GqrGEd"/>
		    </include>
			</control>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow3)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="4300"/>
		      <param name="provider_icon" value="icons/tmdb.png"/>
		      <param name="provider_name" value="$LOCALIZE[31250] (The MovieDB)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(4300).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Posters">
		      <param name="container_id" value="4300"/>
		      <param name="onup" value="4200"/>
		      <param name="ondown" value="4400"/>
		      <param name="content" value="plugin://script.extendedinfo?info=upcomingmovies"/>
		    </include>
			</control>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow4)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="4400"/>
		      <param name="provider_icon" value="icons/youtube.png"/>
		      <param name="provider_name" value="Universal Pictures (YouTube)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(4400).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Landscape">
		      <param name="container_id" value="4400"/>
		      <param name="onup" value="4300"/>
		      <param name="ondown" value="4500"/>
		      <param name="content" value="plugin://script.extendedinfo?info=youtubeplaylistvideos&amp;&amp;id=PLuq_rgCzEP_NBRjFMklzlMaFajjyV-OoL"/>
		    </include>
			</control>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow5)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="4500"/>
		      <param name="provider_icon" value="icons/trakt.png"/>
		      <param name="provider_name" value="$ADDON[script.extendedinfo 32055] (Trakt)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(4500).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Posters">
		      <param name="container_id" value="4500"/>
		      <param name="onup" value="4400"/>
		      <param name="ondown" value="4600"/>
		      <param name="content" value="plugin://script.extendedinfo?info=traktboxofficemovies"/>
		    </include>
			</control>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow6)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="4600"/>
		      <param name="provider_icon" value="icons/youtube.png"/>
		      <param name="provider_name" value="Sony Pictures (YouTube)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(4600).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Landscape">
		      <param name="container_id" value="4600"/>
		      <param name="onup" value="4500"/>
		      <param name="ondown" value="4700"/>
		      <param name="content" value="plugin://script.extendedinfo?info=youtubeplaylistvideos&amp;&amp;id=PLYeOyMz9C9kYmnPHfw5-ItOxYBiMG4amq"/>
		    </include>
			</control>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow7)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="4700"/>
		      <param name="provider_icon" value="icons/trakt.png"/>
		      <param name="provider_name" value="$LOCALIZE[31278] (Trakt)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(4700).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Posters">
		      <param name="container_id" value="4700"/>
		      <param name="onup" value="4600"/>
		      <param name="ondown" value="4800"/>
		      <param name="content" value="plugin://script.extendedinfo?info=mostanticipatedmovies"/>
		    </include>
			</control>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow8)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="4800"/>
		      <param name="provider_icon" value="icons/youtube.png"/>
		      <param name="provider_name" value="Warner Bros. Pictures (YouTube)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(4800).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Landscape">
		      <param name="container_id" value="4800"/>
		      <param name="onup" value="4700"/>
		      <param name="ondown" value="4900"/>
		      <param name="content" value="plugin://script.extendedinfo?info=youtubeplaylistvideos&amp;&amp;id=PLVfin74Qx3tV8bgAhzbfDpnfPoGmJWAcn"/>
		    </include>
			</control>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow9)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="4900"/>
		      <param name="provider_icon" value="icons/trakt.png"/>
		      <param name="provider_name" value="$LOCALIZE[31277] (Trakt)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(4900).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Posters">
		      <param name="container_id" value="4900"/>
		      <param name="onup" value="4800"/>
		      <param name="ondown" value="5000"/>
		      <param name="content" value="plugin://script.extendedinfo?info=mostwatchedmovies"/>
		    </include>
			</control>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow10)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="5000"/>
		      <param name="provider_icon" value="icons/youtube.png"/>
		      <param name="provider_name" value="Fandango MovieClips (YouTube)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(5000).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Landscape">
		      <param name="container_id" value="5000"/>
		      <param name="onup" value="4900"/>
		      <param name="ondown" value="5100"/>
		      <param name="content" value="plugin://script.extendedinfo?info=youtubeplaylistvideos&amp;&amp;id=PLScC8g4bqD47c-qHlsfhGH3j6Bg7jzFy-"/>
		    </include>
			</control>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow11)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="5100"/>
		      <param name="provider_icon" value="icons/trakt.png"/>
		      <param name="provider_name" value="$LOCALIZE[31280] (Trakt)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(5100).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Posters">
		      <param name="container_id" value="5100"/>
		      <param name="onup" value="5000"/>
		      <param name="ondown" value="5200"/>
		      <param name="content" value="plugin://script.extendedinfo?info=traktpopularmovies"/>
		    </include>
			</control>
      
			<control type="group">
			  <width>1230</width>
				<height>280</height>
  			<visible>!Skin.HasSetting(DisableRow12)</visible>
		    <include content="TrailersHeader">
		      <param name="container_id" value="5200"/>
		      <param name="provider_icon" value="icons/youtube.png"/>
		      <param name="provider_name" value="FilmTrailerZone (YouTube)"/>
		      <param name="visible" value="IntegerGreaterThan(Container(5200).NumItems,0)"/>
		    </include>
		    <include content="TrailersPanel_Landscape">
		      <param name="container_id" value="5200"/>
		      <param name="onup" value="5100"/>
		      <param name="ondown" value="4100"/>
		      <param name="content" value="plugin://script.extendedinfo?info=youtubeusersearchvideos&amp;&amp;id=FilmTrailerZone"/>
		    </include>
			</control>
		</control>

		<control type="grouplist">
		  <right>40</right>
		  <top>665</top>
			<width>535</width>
		  <itemgap>6</itemgap>
			<orientation>horizontal</orientation>
	    <include>InfoDialogsVisible_ZoomAnimation</include>
			<include>CommonViews_VerticalAnimation</include>
		  <animation type="Conditional" reversible="false" condition="!Window.IsActive(notification) + !Window.IsActive(extendedprogressdialog)">
	      <include>CommonOpenEffect</include>
		  </animation>
		  <animation type="Conditional" reversible="false" condition="Window.IsActive(notification) | Window.IsActive(extendedprogressdialog)">
	      <include>CommonCloseEffect</include>
		  </animation>
			<control type="label">
				<width>500</width>
				<height>25</height>
			  <align>right</align>
				<font>FontSize_18B</font>
				<label>$LOCALIZE[22082]</label>
				<textcolor>77white</textcolor>
				<scroll>false</scroll>
			</control>
			<control type="image">
				<width>22</width>
				<height>22</height>
				<aspectratio>stretch</aspectratio>
				<texture background="true">icons/submenu_arrow.png</texture>
				<colordiffuse>77white</colordiffuse>
			</control>
		</control>

		<include>CommonItems</include>

    
    
    
	  <control type="group"  id="9000">
			<left>30</left>
			<top>25</top>
      <include>ShutdownMenuAnimation</include>
      <include>OptionsTopMenuAnimation</include>
      <include>OptionsTopMenuHeader</include>
      
			<control type="grouplist" id="9111">
				<onleft>4000</onleft>
				<onright>4000</onright>
        <include>OptionsTopMenuVars</include>
				<control type="radiobutton" id="281">
          <label>$LOCALIZE[31256] (TMDB)</label>
  				<onclick>Skin.ToggleSetting(DisableRow1)</onclick>
  				<selected>!Skin.HasSetting(DisableRow1)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
				<control type="radiobutton" id="282">
          <label>20th Century Fox</label>
  				<onclick>Skin.ToggleSetting(DisableRow2)</onclick>
  				<selected>!Skin.HasSetting(DisableRow2)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
				<control type="radiobutton" id="283">
          <label>$LOCALIZE[31250] (TMDB)</label>
  				<onclick>Skin.ToggleSetting(DisableRow3)</onclick>
  				<selected>!Skin.HasSetting(DisableRow3)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
				<control type="radiobutton" id="284">
          <label>Universal Pictures</label>
  				<onclick>Skin.ToggleSetting(DisableRow4)</onclick>
  				<selected>!Skin.HasSetting(DisableRow4)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
				<control type="radiobutton" id="285">
          <label>$ADDON[script.extendedinfo 32055] (Trakt)</label>
  				<onclick>Skin.ToggleSetting(DisableRow5)</onclick>
					<selected>!Skin.HasSetting(DisableRow5)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
				<control type="radiobutton" id="286">
          <label>Sony Pictures</label>
  				<onclick>Skin.ToggleSetting(DisableRow6)</onclick>
					<selected>!Skin.HasSetting(DisableRow6)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
				<control type="radiobutton" id="287">
          <label>$LOCALIZE[31278] (Trakt)</label>
  				<onclick>Skin.ToggleSetting(DisableRow7)</onclick>
					<selected>!Skin.HasSetting(DisableRow7)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
				<control type="radiobutton" id="288">
          <label>Warner Bros. Pictures</label>
  				<onclick>Skin.ToggleSetting(DisableRow8)</onclick>
					<selected>!Skin.HasSetting(DisableRow8)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
				<control type="radiobutton" id="289">
          <label>$LOCALIZE[31277] (Trakt)</label>
  				<onclick>Skin.ToggleSetting(DisableRow9)</onclick>
					<selected>!Skin.HasSetting(DisableRow9)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
				<control type="radiobutton" id="290">
          <label>Fandango MovieClips</label>
  				<onclick>Skin.ToggleSetting(DisableRow10)</onclick>
					<selected>!Skin.HasSetting(DisableRow10)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
				<control type="radiobutton" id="291">
          <label>Most Popular Movies (Trakt)</label>
  				<onclick>Skin.ToggleSetting(DisableRow11)</onclick>
					<selected>!Skin.HasSetting(DisableRow11)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
				<control type="radiobutton" id="292">
          <label>FilmTrailerZone</label>
  				<onclick>Skin.ToggleSetting(DisableRow12)</onclick>
					<selected>!Skin.HasSetting(DisableRow12)</selected>
				  <include>TopLeftMenusRadioButton</include>
				</control>
  			<include>OptionsTopMenuEnd</include>
			</control>
	  </control>

		
		
		
		<control type="group">
			<left>45</left>
			<top>25</top>
			<include>ShutdownMenuAnimation</include>
		  <include>InfoDialogs_ContentInfoAnimation</include>
		  <include>VisibleHiddenSlideAnimation</include>
			<include>OpenCloseSlideAnimationTwo</include>
		  <visible>!ControlGroup(9000).HasFocus</visible>
			<control type="grouplist">
				<left>0</left>
				<top>0</top>
				<height>70</height>
				<width>1000</width>
				<align>left</align>
				<itemgap>15</itemgap>
				<orientation>horizontal</orientation>
		    <include>Logo</include>
				<control type="label">
					<include>TopBigLabel</include>
					<label>$LOCALIZE[31018]</label>
				</control>
			</control>
		</control>

		<include>CommonWeatherAndClock</include>

	</controls>
</window>

Thanks

**Comment by mikesilvo164** [comment]
Unfortunately script.extendeinfo is not maintained anymore. You can access trailers using the Video Info screen.
