### ISSUE TITLE
Language flags

### ISSUE THREAD

**Issue by Leatherface75** [mikesilvo164/Aeon-Nox-SiLVO#62]
Since latest changes i can't see Language flags in Subittle Download addon.
Worked perfectly before latest language changes.

**Comment by Leatherface75** [comment]
Since latest changes i can't see Language flags in Subittle Download addon.
Worked perfectly before latest language changes.

**Comment by Leatherface75** [comment]
Flags works in later versions but Swedish flag "sv" is wrong.

**Comment by flensburg2** [comment]
This is still the case. Instead of swedish flag I see a blue and white flag, maybe Israel?! Swedish flag is blue with yellow cross.

**Comment by jewbmx** [comment]
Dont know if you use these for this kinda issue but i used this site to grab a few for my latest project.

https://www.countryflags.com/en/sweden-flag-icon.html
