### ISSUE TITLE
Hard coded LibreELEC branding

### ISSUE THREAD

**Issue by P01da** [mikesilvo164/Aeon-Nox-SiLVO#63]
With the recent emergence of CoreELEC, the hard coded references to LibreELEC require attention. It is confusing to have links to (and within) CoreELEC configuration branded as LibreELEC

**Comment by P01da** [comment]
I note that CoreELEC are in the process of changing their use of service.libreelec.settings to service.coreelec.settings, perhaps your next update could incorporate both?

**Comment by mikesilvo164** [comment]
I have added CoreELEC branding to Leia so I will close this issue now.

Please let me know if there are any problems.
