### ISSUE TITLE
Hard coded texts

### ISSUE THREAD

**Issue by mvalec** [mikesilvo164/Aeon-Nox-SiLVO#64]
Hi,
some hardcoded texts prevent complete localization of the skin. Could you please check the attachment, correct this, and refresh source language file on transifex ?

Thanks

[skin.aeon.nox.silvo.6.0.13-untranslated.txt](https://github.com/mikesilvo164/Aeon-Nox-SiLVO/files/2009024/skin.aeon.nox.silvo.6.0.13-untranslated.txt)

**Comment by mikesilvo164** [comment]
I don't think this is still relevant. If it is feel free to open a new issue.
