### ISSUE TITLE
RSS Feeds

### ISSUE THREAD

**Issue by Wanderer189** [mikesilvo164/Aeon-Nox-SiLVO#72]
Running on android 7.1.2 and Kodi v18 Beta5. The RSS is not working in the Github version as of 11-10-18. I can change to Estuary and it works fine.

**Comment by mikesilvo164** [comment]
I have not touched the code for RSS feeds in a very long time.

Are you sure that it is not set to off in the Main menu section of Skin settings?

**Comment by Wanderer189** [comment]
That was it, I had no idea there was a separate setting in the skin as well. Only had it on in default, Sorry ''bout that.
