### ISSUE TITLE
OSD autohide

### ISSUE THREAD

**Issue by Mecool-KX** [mikesilvo164/Aeon-Nox-SiLVO#77]
Hi,

Thanks for this awesome skin.

I'm trying to find out how autohide the OSD after a few seconds.

Is there any way to set this up?

**Comment by danny1990** [comment]
Can you explain what you mean?

Are you talking about when playing videos and if so the OSD should autohide as long as your mouse isn't on the controls.

**Comment by Mecool-KX** [comment]
Yes, when I'm playing videos or seeing TV, when I push OK button in the tv remote the OSD appers. When I see the OSD doesn't hide until I press RETURN button in the remote. I don't use mouse.

I have the skin in CoreELEC with Kodi 18 RC4, btw

**Comment by kodiultimate** [comment]
There is an standalone script availabe for Kodi
called script.hideosd

Try it

**Comment by Mecool-KX** [comment]
Works perfect!!

Thanks.
