### ISSUE TITLE
Up next addon doesn't work as expected

### ISSUE THREAD

**Issue by Mecool-KX** [mikesilvo164/Aeon-Nox-SiLVO#78]
First of all, thank you very much for this preaty skin

I use **Up Next** addon from official Kodi repository.

https://forum.kodi.tv/showthread.php?tid=336747

This addon works well with other skins, but with Silvo has strange behavior.

When the episode is close to end the pop up with the countdown appers without problems. however, when I click "next" button to view the next episode, it starts well but the countdown stills there with the entire duration of the chapter.

It is posible to fix it?

Thanks in advanced

**Comment by mikesilvo164** [comment]
You would need to seek support for this from the maintainer of that add-on. The skin has not control over what it does.
