### ISSUE TITLE
Missing skin setting on Widgets

### ISSUE THREAD

**Issue by gosukelee** [mikesilvo164/Aeon-Nox-SiLVO#79]
Option to "hide widgets when not focused" is missing, always there and can slow down function. Also the option for "global panel widget info" is missing. with a widget that has one picture, panel widget info is needed. please can you check and update this.

![image](https://user-images.githubusercontent.com/46264565/53740960-432f6080-3e8d-11e9-8b08-b198599f06ba.png)

This picture is from kodi 17, kodi 18  with the newest updated Aeon Nox: silvo does not have the two bottom options you see in the image.

**Comment by mikesilvo164** [comment]
They are not gone just moved. You need to enable them for each Widget now. They are in the Main Menu customizer.
![image](https://i.imgur.com/H4CaXbL.jpg)
