### ISSUE TITLE
Widget style names in Main Menu Customizer can not be translated

### ISSUE THREAD

**Issue by mvalec** [mikesilvo164/Aeon-Nox-SiLVO#80]
Widget style names in Main Menu Customizer (Select widget 1, Select widget 2) are shown as not translated because their names are made from property names (**file: Variables_Widgets.xml, lines: 5 and 9**):

`<value condition="!String.IsEmpty(Container(211).ListItem.Property(widgetStyle)) + !String.IsEmpty(Container(211).ListItem.Property(widgetName))">$INFO[Container(211).ListItem.Property(widgetName)][B]$INFO[Container(211).ListItem.Property(widgetStyle), - ][/B]</value>
`

Please use instead variable **WidgetStyleLabelVar** and **WidgetStyle2LabelVar**:

`<value condition="!String.IsEmpty(Container(211).ListItem.Property(widgetStyle)) + !String.IsEmpty(Container(211).ListItem.Property(widgetName))">$INFO[Container(211).ListItem.Property(widgetName)][B]$VAR[WidgetStyleLabelVar, - ][/B]</value>
`

[Variables_Widgets.zip](https://github.com/mikesilvo164/Aeon-Nox-SiLVO/files/2928143/Variables_Widgets.zip)

**Comment by mikesilvo164** [comment]
Nice catch. Will add that to repo sometime soon.

Thanks!
