### ISSUE TITLE
Unsuitable texts for widget backgrounds

### ISSUE THREAD

**Issue by mvalec** [mikesilvo164/Aeon-Nox-SiLVO#81]
**1. Text "Clear" for individual widget background:**
_(file: Variables_Widgets.xml, lines: 108, 119)_
Text 386 is used for wheater, localized text 386 is not suitable for this purpose (background). Please, use new text, eg. 31762

**2. Text "Clear" for global widget background:**
_(file: Variables_Widgets.xml, Line: 161)
(file: Includes_Select.xml, line: 721)_
Text 192 (I dont know why is different from individual background) is used as a werb, localized text 192 is not suitable for this purpose (background). Please, use other (same as individual background), eg. 31762.

**Comment by mikesilvo164** [comment]
Finally getting to some of these issues so sorry for the late reply but this should be fixed now.

The new string still needs translations though.

[matrix](https://github.com/mikesilvo164/Aeon-Nox-SiLVO/commit/54ef05b6691e975a27c3c84489bd009b3ae6de9d)
[leia](https://github.com/mikesilvo164/Aeon-Nox-SiLVO/commit/f6268817e80d5c8da14cf78778f678c17c918380)

**Comment by mvalec** [comment]
Text 386 is used also in overrides.xml on line 477 and 488. Please, replace this with 31542.
