### ISSUE TITLE
2nd Widget Row

### ISSUE THREAD

**Issue by Wanderer189** [mikesilvo164/Aeon-Nox-SiLVO#87]
Hey Mike, I have a couple custom widgets that I am using for unwatched PPV's (playlists). I have it working fine as far as the widgets themselves. The problem I am having is this: Say there are 2 items appearing in each row of widgets, I watch the 2 items in the bottom row of widgets, the widget will then not show until I add new items that are unwatched. I love this, the issue is if I do that and the bottom row isn't showing, I am not able to navigate up to the top row of widgets. I can go only up to the search icon and no farther..

**Comment by mikesilvo164** [comment]
I don't think this is still an issue cause the search icon has been removed and replaced with a menu item instead. 

If it is still a problem feel free to start a new issue.
