### ISSUE TITLE
Switching to source folder from submenu item in main menu doesn't work anymore in Kodi-18

### ISSUE THREAD

**Issue by chpasha** [mikesilvo164/Aeon-Nox-SiLVO#89]
I saw this issue mentioned multiple times on the forum but no real solution except for workaround that I will mention further. In kodi-17 your could choose a video source folder as a submenu item in the main menu, clicking on it would bring you to this folder, listing it's content. Unfortunately it doesn't work the same way on Kodi-18. If you click on submenu, you get the list of multiple playlists having the same name (of the source folder) and have to click again on one of them to jump into the content. The workaround mentioned on the forum was to create a smart list and put it as a submenu item. Didn't try that, too complicated anyway compared with just referencing a source folder.

**Comment by mikesilvo164** [comment]
Works fine for me. Are you using the latest version of script.skinshortcuts from [GitHub](https://github.com/BigNoid/script.skinshortcuts)?

**Comment by chpasha** [comment]
To tell the truth, I've copied and adjusted the path for the shortcuts that did work from other device and so overcome the problem. I will try to check if the problem still reproducible

**Comment by mikesilvo164** [comment]
Closing. If still an issue please open a new one.
