### ISSUE TITLE
Hard coded texts

### ISSUE THREAD

**Issue by mvalec** [mikesilvo164/Aeon-Nox-SiLVO#92]
Hi,
some hardcoded texts prevent complete localization of the skin:
### **1. File: /16x9/Includes_ViewSettings.xml, line: 244**

```
<control type="radiobutton" id="1521">
			<include>ButtonCommonValues</include>
			<label>   - Sets</label>
```
Instead _Sets_ you can use $LOCALIZE[20434]

### **2. File: /16x9/Includes_ViewSettings.xml, line: 794**
```
<control type="radiobutton" id="1531">
			<include>ButtonCommonValues</include>
			<label>   - InfoPopup</label>
```
Instead _InfoPopup_ you can use $LOCALIZE[31292]

Previously reported in Issue #64

**Comment by mikesilvo164** [comment]
Done.

Thanks 😃 

Any more?

**Comment by mvalec** [comment]
There were some bugs in /shortcuts/overrides.xml in the past, but they are probably fixed.

**Comment by mikesilvo164** [comment]
I just re-coded that so yeah hopefully fixed...

Please close this and open a new one if you find more.

Thanks for letting me know about these.
