### ISSUE TITLE
Adjustment request.

### ISSUE THREAD

**Issue by jewbmx** [mikesilvo164/Aeon-Nox-SiLVO#94]
Was wondering if you could increase the volume bars color mix a little so the second color is seen a little more. My themes black on purple and the volume bars mostly black lol(around 80ish%)

Thanks either way and thanks for keeping the skin going too.

**Comment by mikesilvo164** [comment]
Sorry but I just changed this and I like it the way it is.

If you want to revert the change you can mod it into the skin.

**Comment by jewbmx** [comment]
Its got alot of good to it that makes the extra focus worth it so i can leave it alone lol.

One thing i noticed today tho on a new pc is that when clicking left and going down to the Addon Settings option highlighting it causes a little weird index preview in the middle of the screen showing the letter of the menu item i have behind it. Rarely ever seen it used so its a surpise to have it show up lol, not sure if its a skin issue tho.

**Comment by mikesilvo164** [comment]
Should be fixed now.

**Comment by jewbmx** [comment]
Nice, imma get out your hair now lol.
Found one other thing you could do if ya wanna, all the spare addons in your install section have descriptions besides this new script.embuary.helper one.

But ya, Have a good day.
