### ISSUE TITLE
Ajustment in video list

### ISSUE THREAD

**Issue by JrCs** [mikesilvo164/Aeon-Nox-SiLVO#95]
Hi,

can you decrease a little the size of the font that are affected to the filename of the video (i think it's a font30 or more).

Can you also add other view modes than list and icones ?

**Comment by mikesilvo164** [comment]
If you want a smaller font enable slim list in the skin settings.

What are you talking about? I am pretty sure this skin has the most views out of any of them with a total of 25.

**Comment by JrCs** [comment]
Thanks for the option for the font in the list view.

What i was talking about is in list view. There only 2 view modes: List and Icons.

![screenshot006](https://user-images.githubusercontent.com/83008/62766385-a5bb0700-ba92-11e9-8160-365973d8c959.png)
![screenshot007](https://user-images.githubusercontent.com/83008/62766396-ac497e80-ba92-11e9-9f17-f966fe0d6ff4.png)

**Comment by mikesilvo164** [comment]
Those are the view modes you see for files or non-library areas.

Can't have fancy views and metadata for items not in your library.

**Comment by JrCs** [comment]
Ok thanks
