### ISSUE TITLE
Feature request: add some informations in list view

### ISSUE THREAD

**Issue by JrCs** [mikesilvo164/Aeon-Nox-SiLVO#96]
Hi,

is it possible to add some informations in list view like the estuary skin do ?
An example of the list view in YouTube extension:

![screenshot009](https://user-images.githubusercontent.com/83008/63002188-a75f4300-be75-11e9-8eb8-983b63246ad7.png)

![screenshot008](https://user-images.githubusercontent.com/83008/63002410-294f6c00-be76-11e9-8288-a2a03482529e.png)

**Comment by mikesilvo164** [comment]
That is already possible with the default list. Slim list is purposefully a more basic layout.

![Imgur](https://imgur.com/pA2flXL.png)

Time willing I could add an option to see info in slim list...

**Comment by mikesilvo164** [comment]
Added as an option. Enable it in the sidemenu.
![Imgur](https://imgur.com/hY1TFbV.png)

**Comment by JrCs** [comment]
Thanks a lot.
