### ISSUE TITLE
LibreElec - about texts mishmashed

### ISSUE THREAD

**Issue by mvalec** [mikesilvo164/Aeon-Nox-SiLVO#98]
In file: _service-LibreELEC-Settings-mainWindow.xml_ values or labels for Architekture and Version are exchanged. Lines: 969-970, 981-982.

For **Architecture** label: correct text id should be **608**
For **Version** label: correct text id should be **607**

**Comment by mikesilvo164** [comment]
Fixed!

Thanks 😃
